appfolder/events/models.py
from .. import db, app
from dateutil.parser import parse
from datetime import datetime

db.Model.metadata.reflect(db.engine, schema='public')

class Events(db.Model):

    __tablename__ = 'public.events'
    __table__ = db.Model.metadata.tables[__tablename__]
    event_type = db.relationship("EventTypes", backref="events")

    def to_dict(self):
        return {
            "id": self.id,
            "event_type": self.event_type.to_dict(),
            "created_at": str(self.created_at),
            "start": None if self.start is None else str(self.start),
            "stop": None if self.stop is None else str(self.stop),
            "title": self.title,
            "message": self.message
        }

    def set_attributes(self, title, message, event_type_id, start, stop, change_created=True):
        self.title = title
        self.message = message
        self.event_type_id = event_type_id
        if start is not None:
            self.start = parse(start)
        else:
            self.start = None
        if stop is not None:
            self.stop = parse(stop)
        else:
            self.stop = None
        if change_created:
            self.created_at = datetime.utcnow()


class EventTypes(db.Model):

    __tablename__ = 'public.event_types'
    __table__ = db.Model.metadata.tables[__tablename__]

    def to_dict(self):
        return {
            "id": self.id,
            "description": self.description
        }


def _commit(event):
    try:
        db.session.add(event)
        db.session.commit()
    except Exception as e:
        app.logger.error("commit_event - %s" % repr(e))
        db.session.rollback()
        return None
    return event


def get_events():
    return Events.query.all()


def get_event(event_id):
    event = Events.query.get(event_id)
    if event is None:
        app.logger.error("get_event, could not find event with id {}".format(event_id))
    return event


def create_event(title, message, event_type_id, start=None, stop=None):
    event = Events()
    event.set_attributes(title, message, event_type_id, start=None, stop=None)
    return _commit(event)


def update_event(event_id, title, message, event_type_id, start=None, stop=None):
    event = get_event(event_id)

    if event is None:
        return None

    event.set_attributes(title, message, event_type_id, start=None, stop=None, change_created=False)
    return _commit(event)


def delete_event(event_id):
    event = Events.query.get(event_id)

    if event is None:
        return False

    try:
        db.session.delete(event)
        db.session.commit()
    except Exception as e:
        app.logger.error("delete_event - %s" % repr(e))
        db.session.rollback()
        return False
    return True

appfolder/events/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, DateTimeField
from wtforms.validators import InputRequired, Optional, Length


class CreateEventForm(FlaskForm):
    title = StringField("title", validators=[InputRequired(), Length(min=8, max=128)])
    message = StringField("message", validators=[InputRequired(), Length(min=8, max=512)])
    event_type_id = IntegerField("event_type_id", validators=[InputRequired()])
    start = DateTimeField("start", validators=[Optional()], format='%Y-%m-%d %H:%M:%S')
    stop = DateTimeField("stop", validators=[Optional()], format='%Y-%m-%d %H:%M:%S')

    def get_data(self):
        return [self.title.data, self.message.data, self.event_type_id.data, self.start.data, self.stop.data]


class UpdateEventForm(CreateEventForm):
    id = IntegerField("id", validators=[InputRequired()])

    def get_data(self):
        return [self.id.data] + super().get_data()

appfolder/__init__.py
# Import flask and template operators
from flask import Flask

# Import flaks restfull
from flask_restful import Api
from .api_errors import errors_dict

# Import SQLAlchemy
# from flask.ext.sqlalchemy import SQLAlchemy
from flask_sqlalchemy import SQLAlchemy

# Define the application object
app = Flask(__name__, static_url_path="/static")

# Configurations
app.config.from_object('config')

# Define the database object
db = SQLAlchemy(app)

# create api
api = Api(app, errors=errors_dict)
apiurl = "/api/"


# Import a modules / componenst using its blueprint handler
def register_blueprints(app):
    from .events.views import events_module
    events = events_module()
    events.create_routes()
    app.register_blueprint(events.get_blueprint())


# adding resources to the api
def add_resources(api):
    from .events.api import add_resource as events_api
    events_api(api, apiurl)


register_blueprints(app)
add_resources(api)

from .controllers import *

appfolder/controllers.py
from flask import render_template as flask_render
from . import app


@app.route('/', methods=['GET'])
def homepage():

    # Prepare template variables
    template_vars = {
        'menuname': "homepage"
    }

    return render_template('homepage.html', data=template_vars)


def render_template(url, **kwargs):

    kwargs["sys"] = {
        "version": app.config['APP_VERSION'],
        "appname": app.config['APP_NAME'],
        # "wsserver": "%s:%s" % (app.config['WSSERVER_HOST'], app.config["WSSERVER_PORT"])
    }

    if "data" not in kwargs:
        kwargs["data"] = {}

    return flask_render(url, **kwargs)

appfolder/events/controllers.py
from flask import request, jsonify
from sqlalchemy import or_

from .. import app
from ..controllers import render_template
from .models import Events, EventTypes


class events:
    def list(self):

        # Prepare template variables
        template_vars = {
            "ws_server": app.config["WS_SERVER_ENABLED"],
            "ws_server_link": "{0}:{1}".format(app.config['WS_SERVER_HOST'], app.config["WS_SERVER_PORT"]),
            "menuname": "list_events"
        }

        return render_template("events/list.html", data=template_vars)

    def gettable(self):
        # function to populate datatables in list

        fields = ["id", "title", "message", "event_type_id", "start", "stop", "created_at"]

        query = Events.query.join(EventTypes)

        total = query.count()

        search = request.args.get("search")

        if search == "":
            filtered = total
        else:
            query = query.filter(
                or_(
                    Events.title.op('~')('(?i)' + search),
                    EventTypes.description.op('~')('(?i)' + search)
                )
            )
            filtered = query.count()

        order_by = int(request.args.get("order"))

        if order_by == 3:
            query = query.order_by(
                getattr(EventTypes.description, request.args.get("orderdir"))()
            )
        else:
            query = query.order_by(
                getattr(getattr(Events, fields[order_by]), request.args.get("orderdir"))()
            )

        res = query.limit(
            int(request.args.get("length"))
        ).offset(
            int(request.args.get("start"))
        ).all()

        result = [{
            "id": event.id,
            "title": event.title,
            "message": event.message,
            "event_type": event.event_type.description,
            "start": "" if event.start is None else str(event.start),
            "stop": "" if event.stop is None else str(event.stop),
            "created_at": str(event.created_at)
        } for event in res]

        return jsonify({"data": result, "draw": int(request.args.get("draw")), "recordsTotal": total, "recordsFiltered": filtered})

appfolder/events/views.py
from flask import Blueprint
from .controllers import events


class events_module(events):
    def __init__(self):
        # Define the blueprint: 'events', set its url prefix: app.url/events
        # Both static and templates folder are set to local dir
        self.blueprint = Blueprint(
            'events',
            __name__,
            url_prefix='/events',
            static_folder='static',
            template_folder='./templates'
        )

    def get_blueprint(self):
        return self.blueprint

    def create_routes(self):
        @self.blueprint.route("/", methods=['GET'])
        def list():
            return self.list()

        @self.blueprint.route("/gettable/", methods=['GET'])
        def gettable():
            return self.gettable()

appfolder/templates/footer.html
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version:</b> {{sys.version}}
    </div>
    <strong>Created by <a href="https://www.linkedin.com/in/dominic-santos-b0a7bb129/">Dominic Santos</a> for <a href="https://lockwoodpublishing.com/">Lockwood Publishing</a></strong> 
</footer>

appfolder/templates/head.html
<head>
    {% include 'title.html' %}
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}?v={{sys.version}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/font-awesome.min.css')}}?v={{sys.version}}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/ionicons.min.css')}}?v={{sys.version}}">
    <!-- DataTables -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/dataTables.bootstrap.min.css')}}?v={{sys.version}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/AdminLTE.min.css')}}?v={{sys.version}}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins-->
    <link rel="stylesheet" href="{{url_for('static', filename='css/all-skins.min.css')}}?v={{sys.version}}">
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

    <link rel="stylesheet" href="{{url_for('static', filename='css/main.css')}}?v={{sys.version}}">
</head>

appfolder/templates/homepage.html
{% extends "layout.html" %}

{% block content %}
    <section class="content-header">
        <h1>
            Homepage
            <small></small>
        </h1>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box collapsed-box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Backend Challenge Info</h3>

                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                            <i class="fa fa-plus"></i></button>
                        </div>
                    </div>
                    <div class="box-body" style="display: none;">
                        <p>We kindly ask that you complete the below assignment as part of your application.</p>

                        <p>Imagine you've been asked to design and implement a timeline of events happening in a company.</p>

                        <p>You decided to write an API that will allow the register of events in order to display them later. Examples of events are:</p>
                        <ul>
                            <li>Deployment of the fresh release of the game your company makes.</li>
                            <li>Changes of configuration for upcoming event in the game.</li>
                            <li>Game outage, affecting one or more mobile platforms.</li>
                            <li>Some other events of your choice (please think what other events can occur in the system).</li>
                        </ul>

                        <p>Task:</p>
                        <ol>
                            <li>Implement API to store and retrieve events using framework of your choice.</li>
                            <li>API should allow to filter events at least by event type.</li>
                            <li>Implement a simple web page to display the events or CLI.</li>
                            <li>If possible - web page or cli should display events in real time (receive updates).</li>
                        </ol>

                        <p>Only python3.</p>
                    </div>
                </div>
                <div class="box collapsed-box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Database Info</h3>

                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                            <i class="fa fa-plus"></i></button>
                        </div>
                    </div>
                    <div class="box-body" style="display: none;">
                         <iframe width="100%" height="400" src='https://dbdiagram.io/embed/5ec51ed839d18f5553ff8030'> </iframe> 
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block extrajs %}
{% endblock %}

appfolder/templates/layout.html
<!DOCTYPE html>
<html>
    {% include 'head.html' %}
    <body class="skin-blue sidebar-mini wysihtml5-supported" id="main-panel">

        <div class="wrapper">
            {% include 'navbar.html' %}
    
            <div class="content-wrapper">
                {% block content %}
                    default content
                {% endblock %}
            </div>

            {% include 'footer.html' %}

            <aside class="control-sidebar control-sidebar-dark"></aside>
            <div class="control-sidebar-bg"></div>
        </div>

        {% include 'scripts.html' %}

        {% block extrajs %}
        {% endblock %}
    </body>
</html>

appfolder/templates/menu.html
<ul class="sidebar-menu" data-widget="tree">
    <li>
        <a href="{{url_for('homepage')}}" {% if data.menuname == "homepage" %}class="active-page"{% endif %}>
            <i class="fa fa-home"></i>
            <span>Home</span>
        </a>
    </li>
    <li>
        <a href="{{url_for('events.list')}}" {% if data.menuname == "list_events" %}class="active-page"{% endif %}>
            <i class="fa fa-calendar-check-o"></i>
            <span>Events</span>
        </a>
    </li>
</ul>

appfolder/templates/navbar.html
<header class="main-header">
    <!-- Logo -->
    <a class="logo text-center">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <img class="logo-mini" src="{{url_for('static', filename='images/lkwd-logo-small.png')}}?v={{sys.version}}">
        <!-- logo for regular state and mobile devices -->
        <img class="logo-lg" src="{{url_for('static', filename='images/lkwd-logo.png')}}?v={{sys.version}}">
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">

            <ul class="nav navbar-nav">
                <!-- User Account -->
                <!-- <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
                        Username <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="/somewhere">Menu Item</a></li>
                    </ul>
                </li> -->
                <!-- Control Sidebar Toggle Button -->
                <!-- <li>
                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li> -->
            </ul>
        </div>
    </nav>
</header>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <section class="sidebar">

        {% include 'menu.html' %}
        
    </section>
</aside>

appfolder/templates/scripts.html
<script src="{{url_for('static', filename='js/jquery.min.js')}}?v={{sys.version}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{url_for('static', filename='js/jquery-ui.min.js')}}?v={{sys.version}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{url_for('static', filename='js/bootstrap.min.js')}}?v={{sys.version}}"></script>
<!-- DataTables -->
<script src="{{url_for('static', filename='js/jquery.dataTables.min.js')}}?v={{sys.version}}"></script>
<script src="{{url_for('static', filename='js/dataTables.bootstrap.min.js')}}?v={{sys.version}}"></script>
<!-- FastClick -->
<script src="{{url_for('static', filename='js/fastclick.js')}}?v={{sys.version}}"></script>
<!-- AdminLTE App -->
<script src="{{url_for('static', filename='js/adminlte.js')}}?v={{sys.version}}"></script>

appfolder/templates/title.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>{{sys.appname|title}} - {{sys.version}}</title>
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<meta name="robots" content="noindex,nofollow">
<!-- Favicon -->
<link rel="icon" type="image/png" href="{{ url_for('static', filename='images/LKWD_emblem.png')}}?v={{sys.version}}">